name: Check AWS Terraform Code

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  check:
    name: "Check AWS Terraform Code"
    permissions:
      contents: read
      id-token: write
    uses: launchbynttdata/launch-workflows/.github/workflows/reusable-terraform-check-aws.yml@0.6.0
    with:
      assume_role_arn: ${{ vars.TERRAFORM_CHECK_AWS_ASSUME_ROLE_ARN }}
      region: ${{ vars.TERRAFORM_CHECK_AWS_REGION }}
    secrets: inherit # pragma: allowlist secret
